EXTRA_CFLAGS := -I$(src)/chips -I$(src)/common/inc -DMETER_DEV_INIT="$(MY_INITS)" -DMETER_DEV_EXTERNS="$(MY_EXTERNS)" -DMETER_NUM_DEVS=$(NUM_METERS)


obj-m := meters.o
meters-y := common/src/meter.o common/src/meter_fops.o common/src/meter_phy.o chips/mcp3201.o

include $(src)/Kbuild_inc
