EXTRA_CFLAGS := -I$(src)/common/inc -DMETER_DEV_INIT="$(MY_INITS)" -DMETER_DEV_EXTERNS="$(MY_EXTERNS)" -DMETER_NUM_DEVS=$(NUM_METERS)


obj-m := meters.o
meters-y := common/src/meter.o 

include $(src)/Kbuild_inc
